// The only server logic on an otherwise fully static site (user decision,
// 2026-08-03 — both forms were previously a client-only fake setTimeout):
//   POST /api/contact    → contact form, sent via Cloudflare Email
//   POST /api/subscribe  → newsletter signup, added to the Mailchimp audience
// Everything else is served by the `assets` binding — see wrangler.jsonc for
// why that needs no special routing config here (static files win by default;
// these handlers only run for those two paths, which match no file).
//
// `Env` (EMAIL: SendEmail, ASSETS: Fetcher) comes from worker-configuration.d.ts,
// generated by `npx wrangler types` from wrangler.jsonc — regenerate that file
// if the bindings change, don't hand-edit the types.
//
// Two inboxes, chosen by the form's "about" enquiry-type field: partner
// enquiries go to Partnerships, everything else (general contact, speaker
// applications — there's no separate speaker inbox) goes to the general one.
const GENERAL_INBOX = 'hello@ummahtech.net';
const PARTNER_INBOX = 'partners@ummahtech.net';

// Must be a mailbox on a domain onboarded to Cloudflare Email Sending
// (ummahtech.net) — sends fail with E_SENDER_NOT_VERIFIED otherwise. Doesn't
// need to be a real inbox itself; replyTo is what staff actually reply to.
const FROM = { name: 'Ummah Tech website', email: 'forms@ummahtech.net' };

const ENQUIRY_LABELS: Record<string, string> = {
  contact: 'Contact Us',
  speaker: 'Speaker application',
  partner: 'Partner enquiry',
};

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// MAILCHIMP_API_KEY is a secret (`wrangler secret put MAILCHIMP_API_KEY`), so
// it is not declarable in wrangler.jsonc and never appears in the generated
// worker-configuration.d.ts — hence this intersection. The other two are
// plain vars in wrangler.jsonc.
type WorkerEnv = Env & {
  MAILCHIMP_API_KEY?: string;
  MAILCHIMP_LIST_ID?: string;
  MAILCHIMP_SERVER_PREFIX?: string;
};

function escapeHtml(value: string): string {
  return value.replace(
    /[&<>"']/g,
    (c) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#39;',
      })[c] as string,
  );
}

async function handleContact(request: Request, env: Env): Promise<Response> {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return Response.json(
      { ok: false, error: 'Malformed submission.' },
      { status: 400 },
    );
  }

  const name = String(form.get('name') ?? '').trim();
  const email = String(form.get('email') ?? '').trim();
  const message = String(form.get('message') ?? '').trim();
  const about = String(form.get('about') ?? 'contact').trim();

  // The client marks name/email/message `required`, but that's a UX nicety a
  // direct POST bypasses entirely — this is the check that actually holds.
  if (!name || !email || !message) {
    return Response.json(
      { ok: false, error: 'Missing required fields.' },
      { status: 400 },
    );
  }
  if (!EMAIL_PATTERN.test(email)) {
    return Response.json(
      { ok: false, error: 'Invalid email address.' },
      { status: 400 },
    );
  }

  const label = ENQUIRY_LABELS[about] ?? ENQUIRY_LABELS.contact;
  const to = about === 'partner' ? PARTNER_INBOX : GENERAL_INBOX;

  try {
    await env.EMAIL.send({
      to,
      from: FROM,
      // The submitter's own address, so hitting Reply in the inbox goes
      // straight to them rather than to the no-reply sending address.
      replyTo: email,
      subject: `[${label}] ${name}`,
      text: `${label}\n\nFrom: ${name} <${email}>\n\n${message}`,
      html:
        `<p><strong>${escapeHtml(label)}</strong></p>` +
        `<p>From: ${escapeHtml(name)} &lt;${escapeHtml(email)}&gt;</p>` +
        `<p>${escapeHtml(message).replace(/\n/g, '<br>')}</p>`,
    });
  } catch (err) {
    console.error('contact form send failed', err);
    return Response.json(
      { ok: false, error: 'Could not send — please try again.' },
      { status: 502 },
    );
  }

  return Response.json({ ok: true });
}

// --- Newsletter → Mailchimp ------------------------------------------------

/** Mailchimp keys the member resource by MD5 of the lowercased address. MD5 is
 *  not in the WebCrypto standard but Cloudflare Workers support it as a
 *  non-standard extension, which is what makes the idempotent PUT possible
 *  here (POST /members would 400 on anyone who already exists). */
async function md5Hex(value: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    'MD5',
    new TextEncoder().encode(value),
  );
  return [...new Uint8Array(digest)]
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

async function handleSubscribe(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const apiKey = env.MAILCHIMP_API_KEY;
  const listId = env.MAILCHIMP_LIST_ID;
  // Mailchimp API keys end in their data centre, e.g. "...-us21"; fall back to
  // that rather than making the prefix a second thing to configure.
  const server = env.MAILCHIMP_SERVER_PREFIX || apiKey?.split('-').pop();

  if (!apiKey || !listId || !server) {
    console.error('mailchimp not configured', {
      hasKey: Boolean(apiKey),
      hasList: Boolean(listId),
      hasServer: Boolean(server),
    });
    return Response.json(
      { ok: false, error: 'Newsletter is not configured yet.' },
      { status: 503 },
    );
  }

  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return Response.json(
      { ok: false, error: 'Malformed submission.' },
      { status: 400 },
    );
  }

  const email = String(form.get('email') ?? '')
    .trim()
    .toLowerCase();
  if (!EMAIL_PATTERN.test(email)) {
    return Response.json(
      { ok: false, error: 'Please enter a valid email address.' },
      { status: 400 },
    );
  }

  const res = await fetch(
    `https://${server}.api.mailchimp.com/3.0/lists/${listId}/members/${await md5Hex(email)}`,
    {
      method: 'PUT',
      headers: {
        // Basic auth, any username — Mailchimp only reads the password half.
        Authorization: `Basic ${btoa(`anystring:${apiKey}`)}`,
        'content-type': 'application/json',
      },
      // `subscribed` = single opt-in: on the list immediately, no confirmation
      // email (user decision, 2026-08-03). Only applies to NEW addresses;
      // existing members are left exactly as they are, which is why this is
      // safe to re-submit. Switch to 'pending' for double opt-in.
      //
      // NOTE: Mailchimp's audience-level "double opt-in" setting overrides
      // this — if that toggle is on, new addresses still get a confirmation
      // email regardless of what's sent here. Turn it off under Audience →
      // Settings → Audience name and defaults if signups aren't landing as
      // subscribed straight away.
      body: JSON.stringify({
        email_address: email,
        status_if_new: 'subscribed',
      }),
    },
  );

  if (res.ok) return Response.json({ ok: true });

  const detail = await res.text();
  // Someone who previously unsubscribed can't be re-added by us — Mailchimp
  // requires they opt back in themselves. Not an error worth alarming the
  // visitor about, so treat it as done rather than showing a failure.
  if (res.status === 400 && /compliance state/i.test(detail)) {
    return Response.json({ ok: true });
  }
  console.error('mailchimp subscribe failed', res.status, detail);
  return Response.json(
    { ok: false, error: 'Could not sign you up — please try again.' },
    { status: 502 },
  );
}

export default {
  async fetch(request, env): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === 'POST' && url.pathname === '/api/contact') {
      return handleContact(request, env);
    }
    if (request.method === 'POST' && url.pathname === '/api/subscribe') {
      return handleSubscribe(request, env);
    }
    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<WorkerEnv>;
